### ISSUE TITLE
Is there an issue with driver time based UUIDs

### ISSUE THREAD

**Issue by DBatOWL** [valchkou/cassandra-driver-mapping#47]
Just a question, I see in the docs it's suggested to bring in a 3rd party lib to do time based UUID, but since the datastax core libs are already included as part of this driver, why not just use the utils.UUIDs class?  Is there a known issue with that class that we really should be worrying about?

**Comment by valchkou** [comment]
There is no issue with the driver utility.
I inherited my sample from non-datastax app.

Thanks for the catch, I will update doc accordingly.
