### ISSUE TITLE
Could you put the option of adding custom indexes on the annotations?

### ISSUE THREAD

**Issue by rdevis** [valchkou/cassandra-driver-mapping#48]
It's just that I have a custom index on one of my tables, and because I can't put it on the annotation the SchemaSync deletes it.

**Comment by valchkou** [comment]
Did you try this ?

@Table (name="mytable", 
indexes = {
    @Index(name="entity_email_idx", columnList="email" ), 
    @Index(name="entity_name_idx", columnList="myname" ) 
})

**Comment by rdevis** [comment]
Thanks! That did the trick. I thought that it would not work with custom indexes.
