### ISSUE TITLE
Cannot map "long" type in POJO to "timestamp" type in Cassandra

### ISSUE THREAD

**Issue by vshardul** [valchkou/cassandra-driver-mapping#49]
I am creating the schema in AVRO, which does not support the Date type. Hence, have to mark my field type as long. Now, in cassandra, the field is a timestamp. How can i override the field type in the POJO or provide an override method for mapping of fields ? I tried using ColumnDefinition annotation but it does not work. Also, overwriting the mapping dictionary works for writes but reads are broken.

**Comment by valchkou** [comment]
Hi, I am trying to reproduce you case, please confirm
cassandra column type: timestamp
java property type: long

**Comment by vshardul** [comment]
Correct.

**Comment by vshardul** [comment]
Thanks for taking a look !

**Comment by valchkou** [comment]
fixed and should be on mvn central shortly.
use ColumnDefinition annotation:
```java
@Column(columnDefinition="TIMESTAMP") 
private long longstamp; 
```

**Comment by vshardul** [comment]
Thank you !
