### ISSUE TITLE
Optimistic Concurrency using versioning

### ISSUE THREAD

**Issue by nitinpadalia** [valchkou/cassandra-driver-mapping#53]
Hi,
I was wondering how mapping driver is ensuring read operation of Version column is race issue fee?

-Nitin

**Comment by valchkou** [comment]
Sorry, I am not clear of your question.
There is no race condition or blocking on version column on read. 
Version column is read the same way as any other columns.
The only difference is on write:
if what you write has ver different from what is in DB the write will not succeed.
I hope this helps

**Comment by nitinpadalia** [comment]
I mean during write operation does't driver first need to read what's the
current version in db to compare it with the version being written so that
err could be thrown if the version being written is old.

**Comment by valchkou** [comment]
There is no read operation before write.
please read this link to understand the concept
http://www.datastax.com/documentation/cassandra/2.0/cassandra/dml/dml_ltwt_transaction_c.html

I use Lightweight transactions feature provided by Cassandra.
Update statement contains IF condition for proper version (IF version=object.version) 
Cassandra guaranties that update happens only when condition is met.

**Comment by nitinpadalia** [comment]
Ok so it being ensured by LWT, got it thanks!
