### ISSUE TITLE
Timeline for 2.1.7

### ISSUE THREAD

**Issue by DBatOWL** [valchkou/cassandra-driver-mapping#65]
Your driver has been a great tool in developing my app with support for Cassandra (and many thanks for that), when I try to make use of the datastax 2.1.6 driver I get an error about statement caches.  Now that 2.1.7 is released (or about to be), is there any timeline for the release of your driver utilizing the latest datastax driver?

**Comment by valchkou** [comment]
Now I am working on 2.2 whci will use the latest driver version 2.2-RC1. Should be out in 2-3 days

**Comment by DBatOWL** [comment]
Cool!  Thanks for the update.

**Comment by DBatOWL** [comment]
Cool! Thanks for the update.

**Comment by valchkou** [comment]
2.2.0-rc1 released
