### ISSUE TITLE
cassandra version vs cassandra-driver

### ISSUE THREAD

**Issue by pankajmalhotra** [valchkou/cassandra-driver-mapping#69]
Hi,

I am using cassandra-driver-mapping:2.1.5 and cassandra version as 2.0.5?
Do I need to match cassandra version with driver version example:-
com.valchkou.datastax:cassandra-driver-mapping:2.1.5  = cassandra version 2.1.5

OR
com.valchkou.datastax:cassandra-driver-mapping:2.1.5  = cassandra version > 2.xx

Thanks,
Pankaj

**Comment by valchkou** [comment]
cassandra-driver-mapping exactly matches datastax java driver version.
Cassandra has different versioning.
http://docs.datastax.com/en/developer/driver-matrix/doc/common/driverMatrix.html
your version is compatible with  2.0.5

**Comment by pankajmalhotra** [comment]
Whats the compatibility of your library with cassandra version?
Is it the same or different?

Thanks,
Pankaj

**Comment by valchkou** [comment]
the same, my lib based on driver
